use {
    crate::{
        command_title,
        display::json_output,
        loading,
        notify_error,
        notify_success,
        prelude::*,
        sui::*,
    },
    nexus_sdk::{
        idents::{primitives, workflow},
        sui,
        transactions::tool,
    },
    serde_json::{json, Map, Value},
};

/// Register a new onchain tool with automatic schema generation.
/// The input schema is automatically generated by introspecting the Move module's "execute" function.
/// todo: merge this function with the existing `tool_register.rs` function.
/// https://github.com/Talus-Network/nexus/issues/501
pub(crate) async fn register_onchain_tool(
    package_address: sui::ObjectID,
    module_name: String,
    fqn: ToolFqn,
    description: String,
    witness_id: sui::ObjectID,
    no_save: bool,
    sui_gas_coin: Option<sui::ObjectID>,
    sui_gas_budget: u64,
) -> AnyResult<(), NexusCliError> {
    command_title!(
        "Registering Onchain Tool '{fqn}' from package '{package_address}'",
        fqn = fqn,
        package_address = package_address
    );

    // Load CLI configuration.
    let mut conf = CliConf::load().await.unwrap_or_default();

    // Nexus objects must be present in the configuration.
    let objects = &get_nexus_objects(&mut conf).await?;

    // Create wallet context, Sui client and find the active address.
    let mut wallet = create_wallet_context(&conf.sui.wallet_path, conf.sui.net).await?;
    let sui = build_sui_client(&conf.sui).await?;
    let address = wallet.active_address().map_err(NexusCliError::Any)?;

    // Fetch gas coin object.
    let gas_coin = fetch_gas_coin(&sui, address, sui_gas_coin).await?;

    // Fetch reference gas price.
    let reference_gas_price = fetch_reference_gas_price(&sui).await?;

    // Generate input schema by introspecting the Move module's "execute" function.
    notify_success!("Auto-generating input schema from Move module...");
    let base_input_schema = match generate_input_schema(&sui, package_address, &module_name, "execute").await {
        Ok(schema) => {
            notify_success!(
                "Generated base input schema: {}",
                schema.truecolor(100, 255, 100)
            );
            schema
        }
        Err(e) => {
            notify_error!(
                "Failed to generate input schema for tool '{fqn}': {error}",
                fqn = fqn.to_string().truecolor(100, 100, 100),
                error = e
            );
            return Err(e);
        }
    };

    // Allow user to customize parameter descriptions.
    let input_schema = match customize_parameter_descriptions(base_input_schema) {
        Ok(schema) => {
            notify_success!("Parameter descriptions customized successfully!");
            schema
        }
        Err(e) => {
            notify_error!("Failed to customize parameter descriptions: {}", e);
            return Err(e);
        }
    };

    // Craft a TX to register the tool.
    let tx_handle = loading!("Crafting transaction...");

    let mut tx = sui::ProgrammableTransactionBuilder::new();

    if let Err(e) = tool::register_on_chain_for_self(
        &mut tx,
        objects,
        package_address,
        module_name.clone(),
        input_schema.clone(),
        &fqn,
        description.clone(),
        witness_id,
        address.into(),
    ) {
        tx_handle.error();

        return Err(NexusCliError::Any(e));
    }

    tx_handle.success();

    let tx_data = sui::TransactionData::new_programmable(
        address,
        vec![gas_coin.object_ref()],
        tx.finish(),
        sui_gas_budget,
        reference_gas_price,
    );

    // Sign and submit the TX.
    let response = match sign_and_execute_transaction(&sui, &wallet, tx_data).await {
        Ok(response) => response,
        // If the tool is already registered, we don't want to fail the
        // command.
        Err(NexusCliError::Any(e)) if e.to_string().contains("register_on_chain_tool_") => {
            notify_error!(
                "Tool '{fqn}' is already registered.",
                fqn = fqn.to_string().truecolor(100, 100, 100)
            );

            json_output(&json!({
                "tool_fqn": fqn,
                "already_registered": true,
            }))?;

            return Ok(());
        }
        // Any other error fails the tool registration.
        Err(e) => {
            notify_error!(
                "Failed to register tool '{fqn}': {error}",
                fqn = fqn.to_string().truecolor(100, 100, 100),
                error = e
            );

            return Err(e);
        }
    };

    // Parse the owner cap object IDs from the response.
    let owner_caps = response
        .object_changes
        .unwrap_or_default()
        .into_iter()
        .filter_map(|change| match change {
            sui::ObjectChange::Created {
                object_type,
                object_id,
                ..
            } if object_type.address == *objects.primitives_pkg_id
                && object_type.module
                    == primitives::OwnerCap::CLONEABLE_OWNER_CAP.module.into()
                && object_type.name
                    == primitives::OwnerCap::CLONEABLE_OWNER_CAP.name.into() =>
            {
                Some((object_id, object_type))
            }
            _ => None,
        })
        .collect::<Vec<_>>();

    // Find `CloneableOwnerCap<OverTool>` object ID.
    let over_tool = owner_caps.iter().find_map(|(object_id, object_type)| {
        match object_type.type_params.first() {
            Some(sui::MoveTypeTag::Struct(what_for))
                if what_for.module == workflow::ToolRegistry::OVER_TOOL.module.into()
                    && what_for.name == workflow::ToolRegistry::OVER_TOOL.name.into() =>
            {
                Some(object_id)
            }
            _ => None,
        }
    });

    let Some(over_tool_id) = over_tool else {
        return Err(NexusCliError::Any(anyhow!(
            "Could not find the OwnerCap<OverTool> object ID in the transaction response."
        )));
    };

    notify_success!(
        "OwnerCap<OverTool> object ID: {id}",
        id = over_tool_id.to_string().truecolor(100, 100, 100)
    );

    // Note: Onchain tools don't create OverGas caps, so we only save the OverTool cap
    notify_success!("Onchain tools use a different gas model. No OverGas cap was created.");

    // Save the owner caps to the CLI conf.
    if !no_save {
        let save_handle = loading!("Saving the owner cap to the CLI configuration...");

        let mut conf = CliConf::load().await.unwrap_or_default();

        // For onchain tools, we only have OverTool cap, use a placeholder for OverGas
        // TODO: Update ToolOwnerCaps structure to support onchain tools?
        conf.tools.insert(
            fqn.clone(),
            ToolOwnerCaps {
                over_tool: *over_tool_id,
                over_gas: sui::ObjectID::ZERO, // Placeholder
            },
        );

        if let Err(e) = conf.save().await {
            save_handle.error();

            return Err(NexusCliError::Any(e));
        }

        save_handle.success();
    }

    json_output(&json!({
        "digest": response.digest,
        "tool_fqn": fqn,
        "package_address": package_address.to_string(),
        "module_name": module_name,
        "witness_id": witness_id.to_string(),
        "description": description,
        "input_schema": input_schema,
        "owner_cap_over_tool_id": over_tool_id,
        "owner_cap_over_gas_id": null,
        "already_registered": false,
    }))?;

    Ok(())
}

/// Generate input schema by introspecting the Move module's execute function.
async fn generate_input_schema(
    sui: &sui::Client,
    package_address: sui::ObjectID,
    module_name: &str,
    execute_function: &str,
) -> AnyResult<String, NexusCliError> {
    let fetching_handle = loading!("Fetching Move module information...");

    // Fetch all normalized Move modules for the package.
    let all_modules = match sui
        .read_api()
        .get_normalized_move_modules_by_package(package_address)
        .await
    {
        Ok(modules) => {
            fetching_handle.success();
            modules
        }
        Err(e) => {
            fetching_handle.error();
            return Err(NexusCliError::Any(anyhow!(
                "Failed to fetch Move modules for package {}: {}",
                package_address,
                e
            )));
        }
    };

    // Find the specific module.
    let normalized_module = all_modules
        .get(module_name)
        .ok_or_else(|| {
            NexusCliError::Any(anyhow!(
                "Module '{}' not found in package '{}'",
                module_name,
                package_address
            ))
        })?;

    let parsing_handle = loading!("Parsing execute function signature...");

    // Find the execute function.
    let execute_func = normalized_module
        .exposed_functions
        .get(execute_function)
        .ok_or_else(|| {
            NexusCliError::Any(anyhow!(
                "Function '{}' not found in module '{}'",
                execute_function,
                module_name
            ))
        })?;

    // Parse function parameters.
    let mut schema_map = Map::new();
    let mut param_index = 0;

    for (i, param_type) in execute_func.parameters.iter().enumerate() {
        let is_tx_context = is_tx_context_param(param_type);
        println!("DEBUG: Parameter {}: type={:?}, is_tx_context={}", i, param_type, is_tx_context);
        
        // Skip the first parameter (Promise/ProofOfUID) and the last parameter (TxContext).
        if i == 0 || is_tx_context {
            continue;
        }

        let param_schema = convert_move_type_to_schema(param_type)?;
        schema_map.insert(param_index.to_string(), param_schema);
        param_index += 1;
    }

    parsing_handle.success();

    let schema_json = Value::Object(schema_map);
    let schema_string = serde_json::to_string(&schema_json)
        .map_err(|e| NexusCliError::Any(anyhow!("Failed to serialize schema: {}", e)))?;

    Ok(schema_string)
}

/// Convert a Sui Move normalized type to a JSON schema representation.
/// todo: check for all types and add test.
/// https://github.com/Talus-Network/nexus/issues/502
fn convert_move_type_to_schema(move_type: &sui::MoveNormalizedType) -> AnyResult<Value, NexusCliError> {
    use sui::MoveNormalizedType;
    
    match move_type {
        MoveNormalizedType::Bool => Ok(json!({
            "type": "bool",
            "description": "Boolean value"
        })),
        MoveNormalizedType::U8 => Ok(json!({
            "type": "u8",
            "description": "8-bit unsigned integer"
        })),
        MoveNormalizedType::U16 => Ok(json!({
            "type": "u16", 
            "description": "16-bit unsigned integer"
        })),
        MoveNormalizedType::U32 => Ok(json!({
            "type": "u32",
            "description": "32-bit unsigned integer"
        })),
        MoveNormalizedType::U64 => Ok(json!({
            "type": "u64",
            "description": "64-bit unsigned integer"
        })),
        MoveNormalizedType::U128 => Ok(json!({
            "type": "u128",
            "description": "128-bit unsigned integer"
        })),
        MoveNormalizedType::U256 => Ok(json!({
            "type": "u256",
            "description": "256-bit unsigned integer"
        })),
        MoveNormalizedType::Address => Ok(json!({
            "type": "address",
            "description": "Sui address"
        })),
        MoveNormalizedType::Signer => Ok(json!({
            "type": "signer",
            "description": "Transaction signer"
        })),
        MoveNormalizedType::Vector(inner_type) => {
            let inner_schema = convert_move_type_to_schema(inner_type)?;
            Ok(json!({
                "type": "vector",
                "description": "Vector of values",
                "element_type": inner_schema
            }))
        }
        MoveNormalizedType::Struct { 
            address, 
            module, 
            name, 
            type_arguments: _ 
        } => {
            if address == &sui::FRAMEWORK_PACKAGE_ID.to_string() {
                match (module.as_str(), name.as_str()) {
                    ("object", "ID") => Ok(json!({
                        "type": "object_id",
                        "description": "Sui object ID"
                    })),
                    ("object", "UID") => Ok(json!({
                        "type": "object_id",
                        "description": "Unique identifier for an object"
                    })),
                    ("coin", "Coin") => Ok(json!({
                        "type": "object",
                        "description": "Coin object reference"
                    })),
                    ("tx_context", "TxContext") => Ok(json!({
                        "type": "tx_context",
                        "description": "Transaction context (automatically provided)"
                    })),
                    _ => Ok(json!({
                        "type": "object",
                        "description": format!("{}::{}", module, name)
                    }))
                }
            } else {
                // Custom struct types are treated as object references.
                Ok(json!({
                    "type": "object",
                    "description": format!("{}::{}::{}", address, module, name)
                }))
            }
        }
        MoveNormalizedType::Reference(inner_type) => {
            let inner_schema = convert_move_type_to_schema(inner_type)?;
            Ok(json!({
                "type": "reference",
                "description": "Reference to an object",
                "referenced_type": inner_schema
            }))
        }
        MoveNormalizedType::MutableReference(inner_type) => {
            let inner_schema = convert_move_type_to_schema(inner_type)?;
            if let Value::Object(mut schema_obj) = inner_schema {
                schema_obj.insert("mutable".to_string(), Value::Bool(true));
                Ok(Value::Object(schema_obj))
            } else {
                Ok(json!({
                    "type": "mutable_reference",
                    "description": "Mutable reference to an object",
                    "referenced_type": inner_schema
                }))
            }
        }
        MoveNormalizedType::TypeParameter(_) => Ok(json!({
            "type": "generic",
            "description": "Generic type parameter"
        })),
    }
}

/// Check if a parameter is TxContext (should be excluded from schema).
fn is_tx_context_param(move_type: &sui::MoveNormalizedType) -> bool {
    use sui::MoveNormalizedType;
    
    match move_type {
        MoveNormalizedType::Struct { address, module, name, .. } => {
            // TxContext
            (address == "0x2" || address == &sui::FRAMEWORK_PACKAGE_ID.to_string())
                && module == "tx_context"
                && name == "TxContext"
        }
        MoveNormalizedType::MutableReference(inner_type) => {
            // &mut TxContext
            if let MoveNormalizedType::Struct { address, module, name, .. } = inner_type.as_ref() {
                (address == "0x2" || address == &sui::FRAMEWORK_PACKAGE_ID.to_string())
                    && module == "tx_context"
                    && name == "TxContext"
            } else {
                false
            }
        }
        MoveNormalizedType::Reference(inner_type) => {
            // &TxContext
            if let MoveNormalizedType::Struct { address, module, name, .. } = inner_type.as_ref() {
                (address == "0x2" || address == &sui::FRAMEWORK_PACKAGE_ID.to_string())
                    && module == "tx_context"
                    && name == "TxContext"
            } else {
                false
            }
        }
        _ => false
    }
}

/// Allow the user to customize parameter descriptions interactively.
fn customize_parameter_descriptions(schema_json: String) -> AnyResult<String, NexusCliError> {
    use std::io::{self, Write};
    use serde_json::{Map, Value};

    // Skip interactive prompts in JSON mode.
    if JSON_MODE.load(Ordering::Relaxed) {
        return Ok(schema_json);
    }

    // Parse the schema.
    let mut schema: Map<String, Value> = serde_json::from_str(&schema_json)
        .map_err(|e| NexusCliError::Any(anyhow::anyhow!("Failed to parse schema JSON: {}", e)))?;

    if schema.is_empty() {
        println!("\n{info} No parameters to customize.",
            info = "▶".cyan().bold());
        return Ok(schema_json);
    }

    println!("\n{title}",
        title = "Parameter Descriptions".bold().cyan());
    println!("Customize descriptions for each parameter (press Enter to keep current)");

    // Sort parameter keys to ensure consistent order.
    let mut param_keys: Vec<String> = schema.keys().cloned().collect();
    param_keys.sort_by(|a, b| {
        let a_num: i32 = a.parse().unwrap_or(i32::MAX);
        let b_num: i32 = b.parse().unwrap_or(i32::MAX);
        a_num.cmp(&b_num)
    });

    for param_key in param_keys {
        if let Some(param_obj) = schema.get_mut(&param_key) {
            if let Some(param_map) = param_obj.as_object_mut() {
                let param_type = param_map.get("type")
                    .and_then(|v| v.as_str())
                    .unwrap_or("unknown");
                
                let current_description = param_map.get("description")
                    .and_then(|v| v.as_str())
                    .unwrap_or("No description");

                let is_mutable = param_map.get("mutable")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false);

                let type_display = if is_mutable {
                    format!("&mut {}", param_type)
                } else {
                    param_type.to_string()
                };

                println!(" ");
                println!("{} Parameter {}: {} {}",
                    "▶".purple().bold(),
                    param_key.bold(),
                    type_display.blue().bold(),
                    if is_mutable { "(mutable)".yellow() } else { "".normal() }
                );
                println!("Current: {}", current_description.truecolor(150, 150, 150));
                print!("Custom description (Enter to keep): ");
                io::stdout().flush().unwrap();

                let mut input = String::new();
                io::stdin().read_line(&mut input).unwrap();
                let custom_description = input.trim();

                if !custom_description.is_empty() {
                    param_map.insert("description".to_string(), Value::String(custom_description.to_string()));
                    println!("{} Updated description", "✓".green().bold());
                } else {
                    println!("{} Kept current description", "→".truecolor(150, 150, 150));
                }
            }
        }
    }

    println!(" ");

    // Convert back to JSON string.
    serde_json::to_string(&schema)
        .map_err(|e| NexusCliError::Any(anyhow::anyhow!("Failed to serialize schema: {}", e)))
} 